<a href="https://colab.research.google.com/github/Dhayanshariff/Numpy-Task/blob/main/Numpy_Assignment_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x=np.array([12,18,53,60])
x.size*x.itemsize

32

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [49]:
x = np.array([1,2,3,4,5,6])
print(x[::-1])

[6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [48]:
x=np.arange(9)
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [45]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [41]:
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [128]:
print(np.random.random((3,3,3)))

[[[0.1283113  0.23160775 0.76512616]
  [0.58338847 0.11814919 0.25326113]
  [0.01622104 0.9249755  0.60912565]]

 [[0.86164791 0.26623704 0.19970447]
  [0.60328111 0.83618738 0.1452182 ]
  [0.90692976 0.63799728 0.97803146]]

 [[0.92161356 0.99184295 0.10315849]
  [0.53511535 0.27621319 0.36488445]
  [0.09122633 0.70422485 0.60495125]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
X = np.random.random((10,10))
print(X)
print('Minimum:',X.min())
print('Maximum:',X.max())

[[0.25489228 0.10124483 0.72111443 0.65800191 0.0536425  0.53081675
  0.72606112 0.679061   0.04436636 0.2372338 ]
 [0.56052593 0.27791354 0.0589789  0.22093033 0.38596691 0.02937504
  0.79010103 0.87613223 0.81581364 0.86171095]
 [0.58132638 0.23632475 0.57083188 0.29054491 0.59581645 0.13486744
  0.45952122 0.91144194 0.52862075 0.66901564]
 [0.72976611 0.16025698 0.64405844 0.33922549 0.13037206 0.41372334
  0.03869095 0.3525225  0.32139224 0.33809021]
 [0.59713301 0.35049507 0.62459676 0.65464434 0.5764092  0.19856941
  0.59557401 0.20519781 0.7279065  0.91982376]
 [0.77826528 0.32817475 0.69595541 0.43470172 0.59858137 0.16316637
  0.76100433 0.63819024 0.78599911 0.13135464]
 [0.52947123 0.29711663 0.49983272 0.04035905 0.25211482 0.75432389
  0.99958376 0.8038865  0.6541007  0.10914826]
 [0.36312572 0.54783686 0.65384351 0.90135302 0.40597482 0.93586829
  0.5524081  0.94920409 0.68145037 0.0401714 ]
 [0.77295507 0.27728707 0.6545198  0.32659226 0.41025983 0.61910927
  0.48084866

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
X = np.random.random(30)
print(X)
print('Mean:',X.mean())

[0.27768099 0.94437859 0.33059291 0.06800659 0.30749614 0.71572005
 0.68276757 0.70727224 0.88877688 0.61058836 0.78999866 0.73375919
 0.74594921 0.0675924  0.22917203 0.56341495 0.8604881  0.48031556
 0.49241204 0.33583852 0.35575074 0.32112006 0.80869601 0.32562852
 0.52507436 0.05188758 0.92154932 0.16337352 0.59026175 0.86873146]
Mean: 0.5254764766546597


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [51]:
X=np.ones((10,10),dtype=int)
X[1:-1,1:-1]=0
X

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [52]:
X = np.ones((3,2),dtype=int)
X = np.pad(X,pad_width=1,mode='constant',constant_values=0)
print(X)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
#the corresponding outputs are given below

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [34]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [40]:
X=np.ones((8,8),dtype=int)
X[::2,1::2]=0
X[1::2,::2]=0
print(X)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [53]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [59]:
X = np.array([[0,1],[1,0]])
Y = np.tile(X,(4,4))
print(Y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [62]:
X = np.random.random((5,5))
Result = (X - X.min())/(X.max()-X.min())
print(Result)

[[0.12231871 0.10727612 0.07007199 0.28524876 0.70716457]
 [0.44660973 0.53961928 0.48776921 0.79485801 0.        ]
 [0.07397077 0.623727   0.08724721 0.86890607 0.13347906]
 [0.1652375  0.29886522 0.84187928 1.         0.1569485 ]
 [0.83153039 0.29745279 0.37930272 0.00466679 0.32835899]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [3]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [79]:
# from question, my understanding is that the expected operation is matrix multiplication
A = np.arange(0,30,2)
A = A.reshape(5,3)
print('Matrix A\n\n',A)
B = np.arange(6)
B = B.reshape(3,2)
print('\nMatrix B\n\n',B)
print('\nMatrix Multiplication Result\n\n',A@B)

Matrix A

 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]

Matrix B

 [[0 1]
 [2 3]
 [4 5]]

Matrix Multiplication Result

 [[ 20  26]
 [ 56  80]
 [ 92 134]
 [128 188]
 [164 242]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [89]:
# here the negation is inclusive of 3 and 8
x = np.arange(1,12)
x[((x>2) & (x<=8))] = 0
print(x)

[ 1  2  0  0  0  0  0  0  9 10 11]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [91]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [102]:
# except the last expression 'Z<Z>Z', everything is valid
Z = np.arange(2,5)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[2 3 4]
[  4  27 256]
[2 4 8]
[False False False]
[0.+2.j 0.+3.j 0.+4.j]
[2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# the corresponding outputs are below.
nan
0
array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [110]:
X = np.random.uniform(-5, +5, 10)
print(X)
Y = np.copysign(np.ceil(np.abs(X)),X)
print(Y)

[ 1.1195327  -4.77194769 -3.21826155 -4.60107564  4.83404395  0.36686289
  2.45104697 -2.43623699  3.89294576  1.99158906]
[ 2. -5. -4. -5.  5.  1.  3. -3.  4.  2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [112]:
a = np.arange(1,10)
b = np.arange(5,15,2)
x= np.intersect1d(a,b)
print(x)

[5 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [113]:
np.seterr(all='ignore')
a=np.arange(10)/0
with np.errstate(divide='warn'):
     a=np.arange(10)/0

<ipython-input-113-3e2cfc94d16e>:4: RuntimeWarning: divide by zero encountered in true_divide
  a=np.arange(10)/0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [114]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [115]:
Today=np.datetime64('today','D')
print('Today : ',Today)
Yesterday=Today - np.timedelta64(1,'D')
print('Yesterday : ',Yesterday)
Tomorrow=Today + np.timedelta64(1,'D')
print('Tomorrow : ',Tomorrow)

Today :  2023-01-10
Yesterday :  2023-01-09
Tomorrow :  2023-01-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [120]:
X=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(X)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [127]:
X=np.random.uniform(-5,5,5)
print(X)
print(X-(X%1))
print(np.floor(X))
print(np.ceil(X)-1)
print(X.astype(int))
print(np.trunc(X))

[-3.29593466 -4.40630065 -1.92270505 -1.18082767 -0.54714857]
[-4. -5. -2. -2. -1.]
[-4. -5. -2. -2. -1.]
[-4. -5. -2. -2. -1.]
[-3 -4 -1 -1  0]
[-3. -4. -1. -1. -0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [135]:
A=np.zeros((5,5))
A+=np.arange(0,5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [139]:
def generator():
  for x in range(10):
    yield x

y=np.fromiter(generator(),dtype=int,count=-1)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [152]:
V = np.linspace(0,1,11,endpoint=False)
V[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [157]:
x=np.random.randint(5,25,8)
print(x)
print(np.sort(x))

[21 19 17  6 15  6 10  7]
[ 6  6  7 10 15 17 19 21]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [160]:
x = np.arange(11)
print(x)
np.add.reduce(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


55

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [163]:
a=np.random.randint(1,4,10)
b=np.random.randint(2,6,10)
print(np.allclose(a,b))
print(np.array_equal(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [164]:
h = np.random.randint(2,10,5)
h.flags.writeable=False
# if we try to change the elements of h, we will get an error as it is only readable

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [6]:
Z = np.random.random((10,2))
print(Z,'\n')
X,Y = Z[:,0], Z[:,1]
A = np.sqrt(X**2+Y**2)
print('Polar Coordinates\n',A)

[[0.96654604 0.32397431]
 [0.07205827 0.29006134]
 [0.11590102 0.89276224]
 [0.6063548  0.66058748]
 [0.47950054 0.25161541]
 [0.31812792 0.08113622]
 [0.83012451 0.15817085]
 [0.26853262 0.44731157]
 [0.09532093 0.22007928]
 [0.86031772 0.47044608]] 

Polar Coordinates
 [1.01939718 0.29887786 0.90025411 0.89668388 0.54150816 0.32831152
 0.84505901 0.52172541 0.2398353  0.98054377]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [166]:
x=np.random.random(5)
print(x)
x[np.argmax(x)]=0
x

[0.21179082 0.73454208 0.05425175 0.50234942 0.25270692]


array([0.21179082, 0.        , 0.05425175, 0.50234942, 0.25270692])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [167]:
Z = np.zeros((3,3), [('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(Z)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [170]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [171]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [177]:
np.set_printoptions(threshold=np.nan)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [180]:
x = np.random.uniform(5,20,5)
print(x)
y = 10
z = np.abs(x - y)
index = z.argmin()

print('Closest Value:', x[index])

[ 8.35663217 11.30727592  6.21617806  8.40510468  6.21306317]
Closest Value: 11.307275920745209


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [235]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [8]:
A = np.random.random((100,2))
X,Y = np.atleast_2d(A[:,0],A[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.62611826 0.89445056 ... 0.90159636 0.30786081 0.30584157]
 [0.62611826 0.         0.89820119 ... 0.70308351 0.5434814  0.84262992]
 [0.89445056 0.89820119 0.         ... 0.2947158  0.59319753 0.76657521]
 ...
 [0.90159636 0.70308351 0.2947158  ... 0.         0.59975997 0.87326872]
 [0.30786081 0.5434814  0.59319753 ... 0.59975997 0.         0.33268672]
 [0.30584157 0.84262992 0.76657521 ... 0.87326872 0.33268672 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [182]:
x = np.arange(10, dtype=np.float32)
print(x)
x=x.astype(np.int32, copy=False)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [9]:
from io import StringIO

f = StringIO("1, 2, 3, 4, 5\n 6,  ,  , 7, 8\n ,  , 9,10,11\n")
X = np.genfromtxt(f, delimiter=",", dtype=np.int)
print(X)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-9-ed43b76a677a>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.genfromtxt(f, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [185]:
x = np.arange(4).reshape(2,2)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [236]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [190]:
n = 5
p = 5
x = np.zeros((n,n))
r_c= np.random.choice(range(n*n), p, replace=False)
np.put(x,r_c,[11,88,22,33,44,55,66,77])
print(x)

[[ 0. 33.  0.  0. 22.]
 [ 0.  0.  0.  0.  0.]
 [88.  0.  0. 44.  0.]
 [ 0.  0.  0. 11.  0.]
 [ 0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [192]:
X = np.random.rand(2, 5)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.16160269  0.3735456  -0.05982258 -0.32020821  0.16808787]
 [ 0.33067559 -0.095734   -0.40420067  0.1232254   0.04603368]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [209]:
X = np.random.randint(0,8,(3,3))
print(X,'\n')
print(X[X[:,2].argsort()])

[[7 4 0]
 [5 0 6]
 [2 1 3]] 

[[7 4 0]
 [2 1 3]
 [5 0 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [196]:
X = np.random.randint(0,3,(3,8))
print(X,"\n")
print((~X.any(axis=0)),"\n")

[[1 1 2 2 0 1 2 0]
 [0 0 2 1 2 0 0 0]
 [0 2 0 2 0 1 2 0]] 

[False False False False False False False  True] 



#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [198]:
x = np.random.uniform(5,20,5)
print(x)
y = 15
z = np.abs(x - y)
index = z.argmin()
x[index]

[19.12847444 15.70268779 11.41513691  7.4710989  18.02447754]


15.702687789589458

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [200]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [238]:
#not able to understand question

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [10]:
X = np.random.randint(0,10,(3,4,3,4)) 
sum = X.sum(axis=(-2,-1))
print(sum)

[[54 51 62 54]
 [53 45 66 44]
 [59 53 41 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [212]:
X = np.random.uniform(0,1,(3,3))
print(X,'\n')
Y = np.random.uniform(0,1,(3,3))
print(Y,'\n')
Z = np.dot(X,Y)
print(Z,'\n')
np.diag(Z)

[[0.86218495 0.2424318  0.05446287]
 [0.19471372 0.95990829 0.37584801]
 [0.2716213  0.55633253 0.30641191]] 

[[0.74419614 0.36134128 0.78677309]
 [0.35832744 0.5214749  0.44716072]
 [0.03193109 0.26290401 0.15413749]] 

[[0.73024374 0.45228362 0.79514466]
 [0.50086791 0.66973813 0.64036106]
 [0.4112728  0.46881836 0.50970395]] 



array([0.73024374, 0.66973813, 0.50970395])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [213]:
zero = 3
X = np.array([1,2,3,4,5])
Y = np.zeros(len(X) + (len(X)-1)*(zero))
Y[::zero+1] = X
print(Y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [242]:
A = 2*np.ones((5,5,3))
B = 3*np.ones((5,5))
print(A * B[:,:,None])

[[[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [204]:
X = np.arange(9).reshape(3,3)
print(X)
X[[0,1]] = X[[1,0]]
print("\n",X)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [243]:
C = np.bincount([0,1,5,2,3,6,4,7,9])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 1 2 3 4 5 6 7 9]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [248]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)
print(Z)
print(sliding_window_view(Z, window_shape=2).mean(axis=-1))

[0 1 2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [219]:
# negating a boolean
x = np.random.randint(0,2,10)
print(x,'\n')
print(np.logical_not(x, out=x))

[0 0 1 0 0 1 1 0 0 0] 

[1 1 0 1 1 0 0 1 1 1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [12]:
from numpy.lib.stride_tricks import sliding_window_view
X = np.arange(1, 15, dtype=int)
print(sliding_window_view(X, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [222]:
Z = np.random.randint(1,5,(5,5))
rank = np.linalg.matrix_rank(Z)
print(rank)

5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [225]:
x = np.random.randint(0,5,10)
print(x)
print(np.bincount(x).argmax())

[2 3 4 0 4 1 0 3 2 4]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [252]:
Z = 2*np.ones((16,16))
print(Z,'\n')
block = 4
result = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], block), axis=0),
                                       np.arange(0, Z.shape[1], block), axis=1)

print(result)

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]] 

[[32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [228]:
Z = np.arange(30)
np.random.shuffle(Z)
n = 5
print(Z[np.argsort(Z)[-n:]])

[25 26 27 28 29]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [253]:
X = np.array([("Dhayan", 2.5, 3),
              ("Shariff", 3.6, 2)])
Rec_Array = np.core.records.fromarrays(X.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Rec_Array)

[(b'Dhayan', 2.5, 3) (b'Shariff', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [234]:
x = np.random.randint((1,5,10))
print(x)
print(np.power(x,3),'\n')
print(x*x*x,'\n')
print(np.einsum('i,i,i->i',x,x,x),'\n')

[0 1 4]
[ 0  1 64] 

[ 0  1 64] 

[ 0  1 64] 



#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [254]:
X = np.array([0, 1, 2, 3, 17, 25, 27, 32, 65, 128], dtype=np.uint8)
print(np.unpackbits(X[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 1 0 0 0 1]
 [0 0 0 1 1 0 0 1]
 [0 0 0 1 1 0 1 1]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [259]:
X = np.array([[0,0,0], [0, 1, 0], [1, 0, 1], [1, 1, 1], [1, 1, 1]])
print(X,'\n\n')
Y = np.unique(X, axis=0)
print('Unique rows')
print(Y)

[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 1]] 


Unique rows
[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)